[2023-06-14T03:31:31.420+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_avec_postgres.create_postgres_table manual__2023-06-14T03:22:04.172855+00:00 [queued]>
[2023-06-14T03:31:31.441+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_avec_postgres.create_postgres_table manual__2023-06-14T03:22:04.172855+00:00 [queued]>
[2023-06-14T03:31:31.441+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 6
[2023-06-14T03:31:31.466+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-06-14 03:22:04.172855+00:00
[2023-06-14T03:31:31.475+0000] {standard_task_runner.py:57} INFO - Started process 200 to run task
[2023-06-14T03:31:31.480+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_avec_postgres', 'create_postgres_table', 'manual__2023-06-14T03:22:04.172855+00:00', '--job-id', '1915', '--raw', '--subdir', 'DAGS_FOLDER/dag_avec_postgres.py', '--cfg-path', '/tmp/tmpi3r2grnj']
[2023-06-14T03:31:31.482+0000] {standard_task_runner.py:85} INFO - Job 1915: Subtask create_postgres_table
[2023-06-14T03:31:31.603+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_avec_postgres.create_postgres_table manual__2023-06-14T03:22:04.172855+00:00 [running]> on host 4a7ff00e5bd0
[2023-06-14T03:31:31.787+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ismail' AIRFLOW_CTX_DAG_ID='dag_avec_postgres' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T03:22:04.172855+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-14T03:22:04.172855+00:00'
[2023-06-14T03:31:31.788+0000] {sql.py:262} INFO - Executing: 
            create table if not exist dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2023-06-14T03:31:31.805+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-14T03:31:31.975+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-14T03:31:53.188+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "host.docker.internal" (10.248.178.84), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2023-06-14T03:31:53.204+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_avec_postgres, task_id=create_postgres_table, execution_date=20230614T032204, start_date=20230614T033131, end_date=20230614T033153
[2023-06-14T03:31:53.241+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1915 for task create_postgres_table (connection to server at "host.docker.internal" (10.248.178.84), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 200)
[2023-06-14T03:31:53.259+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T03:31:53.296+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
