[2023-06-14T04:05:00.158+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies.get_sklearn manual__2023-06-14T04:04:58.300774+00:00 [queued]>
[2023-06-14T04:05:00.186+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies.get_sklearn manual__2023-06-14T04:04:58.300774+00:00 [queued]>
[2023-06-14T04:05:00.188+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-14T04:05:00.245+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-06-14 04:04:58.300774+00:00
[2023-06-14T04:05:00.253+0000] {standard_task_runner.py:57} INFO - Started process 2707 to run task
[2023-06-14T04:05:00.259+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies', 'get_sklearn', 'manual__2023-06-14T04:04:58.300774+00:00', '--job-id', '1938', '--raw', '--subdir', 'DAGS_FOLDER/dag_avec_extending.py', '--cfg-path', '/tmp/tmpt1y4vl9l']
[2023-06-14T04:05:00.262+0000] {standard_task_runner.py:85} INFO - Job 1938: Subtask get_sklearn
[2023-06-14T04:05:00.397+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_python_dependencies.get_sklearn manual__2023-06-14T04:04:58.300774+00:00 [running]> on host 4a7ff00e5bd0
[2023-06-14T04:05:00.608+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T04:04:58.300774+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-14T04:04:58.300774+00:00'
[2023-06-14T04:05:00.610+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_avec_extending.py", line 14, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-06-14T04:05:00.634+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dag_with_python_dependencies, task_id=get_sklearn, execution_date=20230614T040458, start_date=20230614T040500, end_date=20230614T040500
[2023-06-14T04:05:00.664+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1938 for task get_sklearn (No module named 'sklearn'; 2707)
[2023-06-14T04:05:00.690+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T04:05:00.725+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
