[2023-06-14T01:26:18.308+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_avec_taskflow.bonjour manual__2023-06-14T01:24:13.104205+00:00 [queued]>
[2023-06-14T01:26:18.337+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_avec_taskflow.bonjour manual__2023-06-14T01:24:13.104205+00:00 [queued]>
[2023-06-14T01:26:18.337+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 6
[2023-06-14T01:26:18.370+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): bonjour> on 2023-06-14 01:24:13.104205+00:00
[2023-06-14T01:26:18.378+0000] {standard_task_runner.py:57} INFO - Started process 8590 to run task
[2023-06-14T01:26:18.382+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_avec_taskflow', 'bonjour', 'manual__2023-06-14T01:24:13.104205+00:00', '--job-id', '1675', '--raw', '--subdir', 'DAGS_FOLDER/dag_avec_taskflow.py', '--cfg-path', '/tmp/tmpfv59tuv0']
[2023-06-14T01:26:18.384+0000] {standard_task_runner.py:85} INFO - Job 1675: Subtask bonjour
[2023-06-14T01:26:18.505+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_avec_taskflow.bonjour manual__2023-06-14T01:24:13.104205+00:00 [running]> on host 857e1d87a73f
[2023-06-14T01:26:18.716+0000] {abstractoperator.py:597} ERROR - Exception rendering Jinja template for task 'bonjour', field 'op_kwargs'. Template: {'nom': XComArg(<Task(_PythonDecoratedOperator): get_name>, 'last_name'), 'prenom': XComArg(<Task(_PythonDecoratedOperator): get_name>, 'first_name'), 'age': XComArg(<Task(_PythonDecoratedOperator): get_age>)}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 158, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom_arg.py", line 373, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at dag_avec_taskflow with key="last_name" is not found!
[2023-06-14T01:26:18.750+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 158, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom_arg.py", line 373, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at dag_avec_taskflow with key="last_name" is not found!
[2023-06-14T01:26:18.760+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_avec_taskflow, task_id=bonjour, execution_date=20230614T012413, start_date=20230614T012618, end_date=20230614T012618
[2023-06-14T01:26:18.807+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1675 for task bonjour (XComArg result from get_name at dag_avec_taskflow with key="last_name" is not found!; 8590)
[2023-06-14T01:26:18.825+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T01:26:18.878+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
