[2023-06-14T03:23:57.886+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_avec_postgres.create_postgres_table manual__2023-06-14T03:12:43.584491+00:00 [queued]>
[2023-06-14T03:23:57.904+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_avec_postgres.create_postgres_table manual__2023-06-14T03:12:43.584491+00:00 [queued]>
[2023-06-14T03:23:57.904+0000] {taskinstance.py:1308} INFO - Starting attempt 7 of 7
[2023-06-14T03:23:57.943+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-06-14 03:12:43.584491+00:00
[2023-06-14T03:23:57.960+0000] {standard_task_runner.py:57} INFO - Started process 201 to run task
[2023-06-14T03:23:57.970+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_avec_postgres', 'create_postgres_table', 'manual__2023-06-14T03:12:43.584491+00:00', '--job-id', '1903', '--raw', '--subdir', 'DAGS_FOLDER/dag_avec_postgres.py', '--cfg-path', '/tmp/tmpym9cqjcw']
[2023-06-14T03:23:57.974+0000] {standard_task_runner.py:85} INFO - Job 1903: Subtask create_postgres_table
[2023-06-14T03:23:58.151+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_avec_postgres.create_postgres_table manual__2023-06-14T03:12:43.584491+00:00 [running]> on host 91aeca6ae2d5
[2023-06-14T03:23:58.477+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ismail' AIRFLOW_CTX_DAG_ID='dag_avec_postgres' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T03:12:43.584491+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-14T03:12:43.584491+00:00'
[2023-06-14T03:23:58.478+0000] {sql.py:262} INFO - Executing: 
            create table if not exist dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2023-06-14T03:23:58.517+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-14T03:23:58.799+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-14T03:24:19.903+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "host.docker.internal" (10.248.178.84), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2023-06-14T03:24:19.948+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dag_avec_postgres, task_id=create_postgres_table, execution_date=20230614T031243, start_date=20230614T032357, end_date=20230614T032419
[2023-06-14T03:24:20.028+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1903 for task create_postgres_table (connection to server at "host.docker.internal" (10.248.178.84), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 201)
[2023-06-14T03:24:20.095+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T03:24:20.157+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
