[2023-06-14T03:33:44.958+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_avec_postgres.create_postgres_table manual__2023-06-14T03:33:32.824476+00:00 [queued]>
[2023-06-14T03:33:44.978+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_avec_postgres.create_postgres_table manual__2023-06-14T03:33:32.824476+00:00 [queued]>
[2023-06-14T03:33:44.979+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 7
[2023-06-14T03:33:45.010+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-06-14 03:33:32.824476+00:00
[2023-06-14T03:33:45.017+0000] {standard_task_runner.py:57} INFO - Started process 364 to run task
[2023-06-14T03:33:45.021+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_avec_postgres', 'create_postgres_table', 'manual__2023-06-14T03:33:32.824476+00:00', '--job-id', '1921', '--raw', '--subdir', 'DAGS_FOLDER/dag_avec_postgres.py', '--cfg-path', '/tmp/tmpvfib_qnt']
[2023-06-14T03:33:45.027+0000] {standard_task_runner.py:85} INFO - Job 1921: Subtask create_postgres_table
[2023-06-14T03:33:45.119+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_avec_postgres.create_postgres_table manual__2023-06-14T03:33:32.824476+00:00 [running]> on host 4a7ff00e5bd0
[2023-06-14T03:33:45.257+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ismail' AIRFLOW_CTX_DAG_ID='dag_avec_postgres' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T03:33:32.824476+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-14T03:33:32.824476+00:00'
[2023-06-14T03:33:45.258+0000] {sql.py:262} INFO - Executing: 
            create table if not exist dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2023-06-14T03:33:45.276+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-14T03:33:45.387+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-14T03:33:45.396+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "172.17.0.1", port 5432 failed: fe_sendauth: no password supplied

[2023-06-14T03:33:45.417+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_avec_postgres, task_id=create_postgres_table, execution_date=20230614T033332, start_date=20230614T033344, end_date=20230614T033345
[2023-06-14T03:33:45.445+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1921 for task create_postgres_table (connection to server at "172.17.0.1", port 5432 failed: fe_sendauth: no password supplied
; 364)
[2023-06-14T03:33:45.483+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T03:33:45.518+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
