[2023-06-14T03:33:54.148+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_avec_postgres.create_postgres_table manual__2023-06-14T03:24:27.976993+00:00 [queued]>
[2023-06-14T03:33:54.173+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_avec_postgres.create_postgres_table manual__2023-06-14T03:24:27.976993+00:00 [queued]>
[2023-06-14T03:33:54.174+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 6
[2023-06-14T03:33:54.212+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-06-14 03:24:27.976993+00:00
[2023-06-14T03:33:54.221+0000] {standard_task_runner.py:57} INFO - Started process 371 to run task
[2023-06-14T03:33:54.246+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_avec_postgres', 'create_postgres_table', 'manual__2023-06-14T03:24:27.976993+00:00', '--job-id', '1924', '--raw', '--subdir', 'DAGS_FOLDER/dag_avec_postgres.py', '--cfg-path', '/tmp/tmpmw36widr']
[2023-06-14T03:33:54.252+0000] {standard_task_runner.py:85} INFO - Job 1924: Subtask create_postgres_table
[2023-06-14T03:33:54.346+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_avec_postgres.create_postgres_table manual__2023-06-14T03:24:27.976993+00:00 [running]> on host 4a7ff00e5bd0
[2023-06-14T03:33:54.504+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ismail' AIRFLOW_CTX_DAG_ID='dag_avec_postgres' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T03:24:27.976993+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-14T03:24:27.976993+00:00'
[2023-06-14T03:33:54.505+0000] {sql.py:262} INFO - Executing: 
            create table if not exist dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2023-06-14T03:33:54.525+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-14T03:33:54.660+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-14T03:33:54.669+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "172.17.0.1", port 5432 failed: fe_sendauth: no password supplied

[2023-06-14T03:33:54.697+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_avec_postgres, task_id=create_postgres_table, execution_date=20230614T032427, start_date=20230614T033354, end_date=20230614T033354
[2023-06-14T03:33:54.725+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1924 for task create_postgres_table (connection to server at "172.17.0.1", port 5432 failed: fe_sendauth: no password supplied
; 371)
[2023-06-14T03:33:54.782+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T03:33:54.820+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
