[2023-06-14T03:20:58.980+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_avec_postgres.create_postgres_table manual__2023-06-14T03:09:47.989255+00:00 [queued]>
[2023-06-14T03:20:59.010+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_avec_postgres.create_postgres_table manual__2023-06-14T03:09:47.989255+00:00 [queued]>
[2023-06-14T03:20:59.011+0000] {taskinstance.py:1308} INFO - Starting attempt 6 of 6
[2023-06-14T03:20:59.047+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-06-14 03:09:47.989255+00:00
[2023-06-14T03:20:59.056+0000] {standard_task_runner.py:57} INFO - Started process 1366 to run task
[2023-06-14T03:20:59.061+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_avec_postgres', 'create_postgres_table', 'manual__2023-06-14T03:09:47.989255+00:00', '--job-id', '1894', '--raw', '--subdir', 'DAGS_FOLDER/dag_avec_postgres.py', '--cfg-path', '/tmp/tmp8wu1qyxt']
[2023-06-14T03:20:59.067+0000] {standard_task_runner.py:85} INFO - Job 1894: Subtask create_postgres_table
[2023-06-14T03:20:59.182+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_avec_postgres.create_postgres_table manual__2023-06-14T03:09:47.989255+00:00 [running]> on host 89e558dce6d9
[2023-06-14T03:20:59.379+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ismail' AIRFLOW_CTX_DAG_ID='dag_avec_postgres' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T03:09:47.989255+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-14T03:09:47.989255+00:00'
[2023-06-14T03:20:59.380+0000] {sql.py:262} INFO - Executing: 
            create table if not exist dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2023-06-14T03:20:59.410+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-14T03:20:59.555+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-14T03:20:59.558+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2023-06-14T03:20:59.580+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dag_avec_postgres, task_id=create_postgres_table, execution_date=20230614T030947, start_date=20230614T032058, end_date=20230614T032059
[2023-06-14T03:20:59.618+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1894 for task create_postgres_table (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 1366)
[2023-06-14T03:20:59.650+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T03:20:59.700+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
